# Generated by Django 3.0.1 on 2020-01-02 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ower',
            new_name='owner',
        ),
    ]
